// <auto-generated />
using System;
using Lease.Infrastructure.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lease.Infrastructure.Migrations
{
    [DbContext(typeof(LeaseDbContext))]
    [Migration("20201124102325_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lease.Domain.Buyer", b =>
                {
                    b.Property<Guid>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BuyerId");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("Lease.Domain.LeaseOrder", b =>
                {
                    b.Property<Guid>("LeaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LeaseOrderId");

                    b.HasIndex("BuyerId");

                    b.ToTable("Leases");
                });

            modelBuilder.Entity("Lease.Domain.LeaseOrderLine", b =>
                {
                    b.Property<Guid>("LeaseOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LeaseOrderLineId");

                    b.HasIndex("LeaseId");

                    b.ToTable("LeaseOrderLines");
                });

            modelBuilder.Entity("Lease.Domain.Buyer", b =>
                {
                    b.OwnsOne("Lease.Domain.BuyerId", "Id", b1 =>
                        {
                            b1.Property<Guid>("BuyerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("BuyerId");

                            b1.ToTable("Buyers");

                            b1.WithOwner()
                                .HasForeignKey("BuyerId");
                        });

                    b.OwnsOne("Lease.Domain.BuyerName", "BuyerName", b1 =>
                        {
                            b1.Property<Guid>("BuyerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BuyerId");

                            b1.ToTable("Buyers");

                            b1.WithOwner()
                                .HasForeignKey("BuyerId");
                        });
                });

            modelBuilder.Entity("Lease.Domain.LeaseOrder", b =>
                {
                    b.HasOne("Lease.Domain.Buyer", "Buyer")
                        .WithMany("LeaseOrders")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Lease.Domain.City", "City", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LeaseOrderId");

                            b1.ToTable("Leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderId");
                        });

                    b.OwnsOne("Lease.Domain.DateCreated", "DateCreated", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2");

                            b1.HasKey("LeaseOrderId");

                            b1.ToTable("Leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderId");
                        });

                    b.OwnsOne("Lease.Domain.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit");

                            b1.HasKey("LeaseOrderId");

                            b1.ToTable("Leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderId");
                        });

                    b.OwnsOne("Lease.Domain.IsDelivery", "IsDelivery", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit");

                            b1.HasKey("LeaseOrderId");

                            b1.ToTable("Leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderId");
                        });

                    b.OwnsOne("Lease.Domain.IsPaid", "IsPaid", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit");

                            b1.HasKey("LeaseOrderId");

                            b1.ToTable("Leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderId");
                        });

                    b.OwnsOne("Lease.Domain.LeaseOrderId", "Id", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("LeaseOrderIdValue")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("LeaseOrderId");

                            b1.ToTable("Leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderId");
                        });

                    b.OwnsOne("Lease.Domain.Street", "Street", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LeaseOrderId");

                            b1.ToTable("Leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderId");
                        });

                    b.OwnsOne("Lease.Domain.TotalPrice", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("LeaseOrderId");

                            b1.ToTable("Leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderId");
                        });

                    b.OwnsOne("Lease.Domain.ZipCode", "ZipCode", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("LeaseOrderId");

                            b1.ToTable("Leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderId");
                        });
                });

            modelBuilder.Entity("Lease.Domain.LeaseOrderLine", b =>
                {
                    b.HasOne("Lease.Domain.LeaseOrder", "LeaseOrder")
                        .WithMany("LeaseOrderLines")
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Lease.Domain.EndDate", "EndDate", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2");

                            b1.HasKey("LeaseOrderLineId");

                            b1.ToTable("LeaseOrderLines");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderLineId");
                        });

                    b.OwnsOne("Lease.Domain.IsReturned", "IsReturned", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit");

                            b1.HasKey("LeaseOrderLineId");

                            b1.ToTable("LeaseOrderLines");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderLineId");
                        });

                    b.OwnsOne("Lease.Domain.LeaseOrderLineId", "Id", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("LeaseOrderLineId");

                            b1.ToTable("LeaseOrderLines");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderLineId");
                        });

                    b.OwnsOne("Lease.Domain.LineTotalPrice", "LineTotalPrice", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("LeaseOrderLineId");

                            b1.ToTable("LeaseOrderLines");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderLineId");
                        });

                    b.OwnsOne("Lease.Domain.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("LeaseOrderLineId");

                            b1.ToTable("LeaseOrderLines");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderLineId");
                        });

                    b.OwnsOne("Lease.Domain.ResourceId", "ResourceId", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("LeaseOrderLineId");

                            b1.ToTable("LeaseOrderLines");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderLineId");
                        });

                    b.OwnsOne("Lease.Domain.ResourceName", "ResourceName", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LeaseOrderLineId");

                            b1.ToTable("LeaseOrderLines");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderLineId");
                        });

                    b.OwnsOne("Lease.Domain.ResourcePrice", "ResourcePrice", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("LeaseOrderLineId");

                            b1.ToTable("LeaseOrderLines");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderLineId");
                        });

                    b.OwnsOne("Lease.Domain.StartDate", "StartDate", b1 =>
                        {
                            b1.Property<Guid>("LeaseOrderLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2");

                            b1.HasKey("LeaseOrderLineId");

                            b1.ToTable("LeaseOrderLines");

                            b1.WithOwner()
                                .HasForeignKey("LeaseOrderLineId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
